package com.cetnaline.findproperty.model.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cetnaline.findproperty.model.database.entity.DropMenu;
import com.cetnaline.findproperty.model.database.entity.GScope;
import com.cetnaline.findproperty.model.database.entity.NearByScope;
import com.cetnaline.findproperty.model.database.entity.RailLine;
import com.cetnaline.findproperty.model.database.entity.RailWay;
import com.cetnaline.findproperty.model.database.entity.School;
import com.cetnaline.findproperty.model.database.entity.Store;

import com.cetnaline.findproperty.model.database.dao.DropMenuDao;
import com.cetnaline.findproperty.model.database.dao.GScopeDao;
import com.cetnaline.findproperty.model.database.dao.NearByScopeDao;
import com.cetnaline.findproperty.model.database.dao.RailLineDao;
import com.cetnaline.findproperty.model.database.dao.RailWayDao;
import com.cetnaline.findproperty.model.database.dao.SchoolDao;
import com.cetnaline.findproperty.model.database.dao.StoreDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dropMenuDaoConfig;
    private final DaoConfig gScopeDaoConfig;
    private final DaoConfig nearByScopeDaoConfig;
    private final DaoConfig railLineDaoConfig;
    private final DaoConfig railWayDaoConfig;
    private final DaoConfig schoolDaoConfig;
    private final DaoConfig storeDaoConfig;

    private final DropMenuDao dropMenuDao;
    private final GScopeDao gScopeDao;
    private final NearByScopeDao nearByScopeDao;
    private final RailLineDao railLineDao;
    private final RailWayDao railWayDao;
    private final SchoolDao schoolDao;
    private final StoreDao storeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dropMenuDaoConfig = daoConfigMap.get(DropMenuDao.class).clone();
        dropMenuDaoConfig.initIdentityScope(type);

        gScopeDaoConfig = daoConfigMap.get(GScopeDao.class).clone();
        gScopeDaoConfig.initIdentityScope(type);

        nearByScopeDaoConfig = daoConfigMap.get(NearByScopeDao.class).clone();
        nearByScopeDaoConfig.initIdentityScope(type);

        railLineDaoConfig = daoConfigMap.get(RailLineDao.class).clone();
        railLineDaoConfig.initIdentityScope(type);

        railWayDaoConfig = daoConfigMap.get(RailWayDao.class).clone();
        railWayDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        dropMenuDao = new DropMenuDao(dropMenuDaoConfig, this);
        gScopeDao = new GScopeDao(gScopeDaoConfig, this);
        nearByScopeDao = new NearByScopeDao(nearByScopeDaoConfig, this);
        railLineDao = new RailLineDao(railLineDaoConfig, this);
        railWayDao = new RailWayDao(railWayDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);

        registerDao(DropMenu.class, dropMenuDao);
        registerDao(GScope.class, gScopeDao);
        registerDao(NearByScope.class, nearByScopeDao);
        registerDao(RailLine.class, railLineDao);
        registerDao(RailWay.class, railWayDao);
        registerDao(School.class, schoolDao);
        registerDao(Store.class, storeDao);
    }
    
    public void clear() {
        dropMenuDaoConfig.clearIdentityScope();
        gScopeDaoConfig.clearIdentityScope();
        nearByScopeDaoConfig.clearIdentityScope();
        railLineDaoConfig.clearIdentityScope();
        railWayDaoConfig.clearIdentityScope();
        schoolDaoConfig.clearIdentityScope();
        storeDaoConfig.clearIdentityScope();
    }

    public DropMenuDao getDropMenuDao() {
        return dropMenuDao;
    }

    public GScopeDao getGScopeDao() {
        return gScopeDao;
    }

    public NearByScopeDao getNearByScopeDao() {
        return nearByScopeDao;
    }

    public RailLineDao getRailLineDao() {
        return railLineDao;
    }

    public RailWayDao getRailWayDao() {
        return railWayDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

}
